bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch41.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch40.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch42.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch44.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch47.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch46.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch45.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch48.mdl WN18RR
bash scripts/eval.sh ./checkpoint/wn18rr_gcn_debug/checkpoint_epoch40.mdl WN18RR
